### ISSUE TITLE
[Feature Request] Integrate RAG-based Language Model for Interactive Q&A 🤖

### ISSUE THREAD

**Issue by kadirnar** [kadirnar/whisper-plus#13]
Integrate the RAG-based Language Model for interactive question and answer functionality. Users can utilize any text input to query their preferred language model. The model will respond with answers derived from the specified document, enhancing user engagement and interactivity. 🤖

Github: [Autollm: Ship RAG based LLM](https://github.com/safevideo/autollm) ⚙️

**Comment by StatKumar** [comment]
@kadirnar Can I work on this issue?

**Comment by kadirnar** [comment]
> @kadirnar Can I work on this issue?
Yes🚀 It would be great if you could use the Autollm library. You can also add other libraries.

**Comment by StatKumar** [comment]
Thank you @kadirnar

**Comment by kadirnar** [comment]
Hi @StatKumar, the autollm library can be difficult. Do you want me to help you? You can ask all your questions. We can send a pull reqest for testing and develop it together.

**Comment by StatKumar** [comment]
@kadirnar Sure. Please guide me through it.

**Comment by StatKumar** [comment]
@kadirnar should we create a roadmap for this task? With smaller milestones

**Comment by StatKumar** [comment]
@kadirnar Also I was trying out the app and I was getting the following:
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.HalfTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

It happens when the device is not switched - cpu to gpu or vice versa

Meanwhile, do you want to create slack channel? so we can discuss it on there.

**Comment by kadirnar** [comment]
Do you use discord app? Can you text me? 

username: kadirnar

**Comment by StatKumar** [comment]
@kadirnar sent you a friend's request on discord.
